version: 2

sources:
  - name: erp
    database: fea24_4
    schema: raw_adventure_works
    tables:
      - name: product
        columns:
          - name: productid
            tests:
              - unique
              - not_null
      - name: productcategory
        columns:
          - name: productcategoryid
            tests:
              - unique
              - not_null
      - name: productsubcategory
        columns:
          - name: productsubcategoryid
            tests:
              - unique
              - not_null
      - name: vendor
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: productvendor
        columns:
          - name: productid
            tests:
              - not_null
      - name: shoppingcartitem
        columns:
          - name: shoppingcartitemid
            tests:
              - unique
              - not_null
      - name: countryregion
        columns:
          - name: countryregioncode
            tests:
              - unique
              - not_null
      - name: stateprovince
        columns:
          - name: stateprovinceid
            tests:
              - unique
              - not_null
      - name: salesterritory
        columns:
          - name: territoryid
            tests:
              - unique
              - not_null
      - name: customer
        columns:
          - name: customerid
            tests:
              - unique
              - not_null
      - name: person
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: salesperson
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: salesorderheadersalesreason
        columns:
          - name: salesorderid
            tests:
              - not_null
      - name: salesreason
        columns:
          - name: salesreasonid
            tests:
              - unique
              - not_null
      - name: salesorderheader
        columns:
          - name: salesorderid
            tests:
              - unique
              - not_null
      - name: salesorderdetail
        columns:
          - name: salesorderdetailid
            tests:
              - unique
              - not_null
      - name: store
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: salesterritoryhistory
        columns:
          - name: businessentityid
            tests:
              - not_null
      - name: salespersonquotahistory
        columns:
          - name: businessentityid
            tests:
              - not_null
      - name: personcreditcard
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: creditcard
        columns:
          - name: creditcardid
            tests:
              - unique
              - not_null
      - name: currencyrate
        columns:
          - name: currencyrateid
            tests:
              - unique
              - not_null
      - name: currency
        columns:
          - name: currencycode
            tests:
              - unique
              - not_null
      - name: salestaxrate
        columns:
          - name: salestaxrateid
            tests:
              - unique
              - not_null
      - name: specialoffer
        columns:
          - name: specialofferid
            tests:
              - not_null
      - name: specialofferproduct
        columns:
          - name: specialofferid
            tests:
              - not_null
      - name: businessentitycontact
        columns:
          - name: businessentityid
            tests:
              - not_null
      - name: address
        columns:
          - name: addressid
            tests:
              - unique
              - not_null
      - name: employee
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: businessentityaddress
        columns:
          - name: businessentityid
            tests:
              - not_null
